version: '3.9'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
    env_file:
      - csvserver.env

  promithious:
    image: prom/prometheus:v2.22.0
    ports:
       - "9090:9090"

volumes:
  inputdata:
